[build]
  base = "/"
  publish = "client/build"
  command = "npm install && npm run build --prefix client && npm install --prefix server"

[functions]
  directory = "server/netlify/functions"


[context.deploy-preview]
  command = "npm install && npm run build --prefix client"
  
[[redirects]]
from = "/api"
to = "/.netlify/functions/api"
status = 200

[[redirects]]
from = "/api/products"
to = "/.netlify/functions/products"
status = 200