[build]
  base = "/"
  publish = "client/build"
  command = "cd client && npm install && npm run build && cd ../server && npm install"

[functions]
  directory = "server/netlify/functions"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/products"
  status = 200

[[redirects]]
  from = "/api/products"
  to = "/.netlify/functions/products"
  status = 200

[context.deploy-preview]
  command = "cd client && npm install && npm run build && cd ../server && npm install"
