[build]
  base = "/"
  publish = "client/build"
  command = "npm install && npm run build --prefix client"

[functions]
  directory = "server/netlify/functions"

  
[[redirects]]
from = "/api"
to = "/.netlify/functions/api"
status = 200

[[redirects]]
from = "/api/products"
to = "/.netlify/functions/products"
status = 200